name: autosense
description: Filippo's coding assignment.
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  http: ^0.13.4
  google_fonts: ^2.1.0
  get_it: ^7.2.0
  injectable: ^1.5.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  flutter_map: ^0.14.0
  flutter_secure_storage: ^5.0.2
  bloc_test: ^9.0.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  injectable_generator: ^1.5.0
  json_serializable: ^6.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg